### ISSUE TITLE
Chore add Unity3D build workflow.

### ISSUE THREAD

**Issue by WuZhuoran** [YiGu-Studio/MB2CommunityEditor#7]
We can refer [unity-builder](https://github.com/marketplace/actions/unity-builder)

and [unity-activate](https://github.com/marketplace/actions/unity-activate)

We should first add our `Unity3D.LICENSE` to organization secrets.

**Comment by hx8888979** [comment]
We may not build the entire unity project. Because it is a unity plugin project and just a part of codes (within the folder "/Assets/MBEditor" specifically) should be built as a library (which is the final distribution form)
The C# project workflow may fit it better

**Comment by WuZhuoran** [comment]
> We may not build the entire unity project. Because it is a unity plugin project and just a part of codes (within the folder "/Assets/MBEditor" specifically) should be built as a library (which is the final distribution form)
> The C# project workflow may fit it better

How about this? https://github.com/marketplace/actions/setup-net-core-sdk
This is pretty common used for all kind of `.Net Core Build` actions.

**Comment by WuZhuoran** [comment]
I think I will first start a workflow with a starter.
https://github.com/actions/starter-workflows/blob/master/ci/dotnet-core.yml
I will quickly start a PR soon.

**Comment by hx8888979** [comment]
I am not sure .net core is compatibility enough for Unity seems to use .net framework 4
